.TH PGPOKE 1
.SH NAME
wingsum \- Parses flighlog and sums up the flight time/count per wing.
.SH SYNOPSIS
.B wingsum
[\fB\--version,\--help\fR]
.IR UID
.SH DESCRIPTION
.B wingsum
Parses flightlog.org and sums up the flight time/count per wing and prints them in a ugly table.
.SH OPTIONS
.TP
.BR UID\fR
The flightlog.org user ID.
.TP
.BR \--version\fR
Prints the version.
.TP
.BR \--help\fR
Prints the help message.
